global:
  # How frequently to scrape targets by default.
  # Default 15s
  scrape_interval: 25s
  # How frequently to evaluate rules.
  # Default 15s
  evaluation_interval: 15s
  # How long until a scrape request times out.
  # Default to 10s.
  # Required because cp-demo is using cpu throttling, so let's leave enough time to fetch the metrics in particular for the first time as it needs to compile all rexps
  scrape_timeout: 20s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "zookeeper"
    static_configs:
      - targets:
          - "zookeeper:2181"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'


  - job_name: "kafka"
    static_configs:
      - targets:
          - "kafka0:12345"
          - "kafka1:12345"
          - "kafka2:12345"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'



  # No producer for the moment in cp-demo
  # - job_name: 'kafka-producer'
  #   static_configs:
  #     - targets:
  #         - 'kafka1:1235'
  #       labels:
  #         env: 'dev'
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: hostname
  #       regex: '([^:]+)(:[0-9]+)?'
  #       replacement: '${1}'

  # No consumer for the moment in cp-demo
  # - job_name: 'kafka-consumer'
  #   static_configs:
  #     - targets:
  #         - "kafka1:1236"
  #       labels:
  #         env: 'dev'
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: hostname
  #       regex: '([^:]+)(:[0-9]+)?'
  #       replacement: '${1}'
